apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: jupyterhub
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: jupyterhub
    version: 0.1.5
    description: An application that you can use to create documents that contain live code, equations, visualizations, and text.
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/6664af69-9133-4d0c-b0db-adf0c8fce072/jupyterhub.png?v=63848545606
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
