apiVersion: v2
name: ingress-nginx
description: A helm chart for ingress-nginx
version: 0.1.0
appVersion: 0.1.13
dependencies:
- name: ingress-nginx
  version: 0.1.13
  repository: cm://app.plural.sh/cm/ingress-nginx
  condition: ingress-nginx.enabled
- name: ingress-nginx-private
  version: 0.1.18
  repository: cm://app.plural.sh/cm/ingress-nginx
  condition: ingress-nginx-private.enabled
